### ISSUE TITLE
Can I use widget here?

### ISSUE THREAD

**Issue by sibelius** [r0b1n/rnrf-relay-example#2]
instead of using node can I use widget?

instead of {node: () => Relay.QL`query { node(id: $nodeID) }`,}} can I do this:

`{widget: () => Relay.QL`query { widget(id: $nodeID) } `,}}` ?

**Comment by r0b1n** [comment]
You can use it if you have `widget` on graphql backend.
Starter kit doesn't contain it. It has only `viewer` and this `node` universal endpoint.

**Comment by sibelius** [comment]
thanks
